[client]
showSidebarNavigation = false
showErrorDetails = true
toolbarMode = "minimal"

[theme]
base = "dark"

#blue 007BFF
#red f3425f
primaryColor = "#007BFF"

backgroundColor = "#ffffff"

#grey F8F9FA
secondaryBackgroundColor = "#GGGGGG"

textColor = "#343A40"

# "sans serif", "serif", or "monospace".
font = "sans serif"